# Shared Python development targets
# Manages conda base environment and Python dev tooling
#
# Requires: Miniforge installed (via devcontainer/setup-base.sh)
# Variables:
#   CONDA_PREFIX           - path to conda installation (default: ~/miniforge3)
#   COMMON_DIR             - path to dev-common (default: common)
#   PACKAGE_DIR            - source directory to scan for imports (default: PROJECT_NAME)
#   PROJECT_CONDA_PACKAGES - path to project-specific conda packages file (optional)
#   REQUIREMENTS_FILE      - output file for production requirements (default: requirements-prod.txt)

CONDA_PREFIX ?= $(HOME)/miniforge3
COMMON_DIR ?= common
PACKAGE_DIR ?= $(PROJECT_NAME)
PROJECT_CONDA_PACKAGES ?=
REQUIREMENTS_FILE ?= requirements-prod.txt

CONDA := $(CONDA_PREFIX)/bin/conda
BASE_PACKAGES := $(COMMON_DIR)/devcontainer/base-conda-packages.txt
DEV_TOOLS := ruff pytest pytest-cov ipykernel jupyterlab pipreqs

.PHONY: env env-info list-imports requirements lint lint-fix format

# -----------------------------------------------------------------------------
# Conda environment
# -----------------------------------------------------------------------------

env: ## install/refresh conda base dev environment
	@echo "==> Installing base conda packages..."
	$(CONDA) install -y --file $(BASE_PACKAGES)
	@if [ -n "$(PROJECT_CONDA_PACKAGES)" ] && [ -f "$(PROJECT_CONDA_PACKAGES)" ]; then \
		echo "==> Installing project conda packages from $(PROJECT_CONDA_PACKAGES)..."; \
		$(CONDA) install -y --file $(PROJECT_CONDA_PACKAGES); \
	fi
	@echo "==> Installing dev tools..."
	$(CONDA) install -y $(DEV_TOOLS)
	@echo "==> Dev environment ready"

env-info: ## show conda environment info
	$(CONDA) info
	@echo ""
	@echo "==> Installed packages:"
	$(CONDA) list

# -----------------------------------------------------------------------------
# Production requirements
# -----------------------------------------------------------------------------

list-imports: ## list imports for production requirements
	@$(CONDA_PREFIX)/bin/pipreqs $(PACKAGE_DIR) --print --mode no-pin 2>/dev/null | sort -u

requirements: ## generate pinned production requirements file
	@echo "==> Scanning imports in $(PACKAGE_DIR)..."
	@IMPORTS=$$($(CONDA_PREFIX)/bin/pipreqs $(PACKAGE_DIR) --print --mode no-pin 2>/dev/null | sort -u); \
	if [ -z "$$IMPORTS" ]; then \
		echo "No imports found in $(PACKAGE_DIR)"; \
		exit 1; \
	fi; \
	echo "# Production requirements - generated by make requirements" > $(REQUIREMENTS_FILE); \
	echo "# Source: pipreqs scan of $(PACKAGE_DIR) with versions from conda env" >> $(REQUIREMENTS_FILE); \
	echo "" >> $(REQUIREMENTS_FILE); \
	for pkg in $$IMPORTS; do \
		version=$$($(CONDA_PREFIX)/bin/conda list --no-pip "^$${pkg}$$" 2>/dev/null | grep -v "^#" | awk '{print $$2}' | head -1); \
		if [ -n "$$version" ]; then \
			echo "$${pkg}==$${version}" >> $(REQUIREMENTS_FILE); \
		else \
			pip_version=$$($(CONDA_PREFIX)/bin/pip show "$$pkg" 2>/dev/null | grep "^Version:" | awk '{print $$2}'); \
			if [ -n "$$pip_version" ]; then \
				echo "$${pkg}==$${pip_version}" >> $(REQUIREMENTS_FILE); \
			else \
				echo "$${pkg}" >> $(REQUIREMENTS_FILE); \
			fi; \
		fi; \
	done; \
	echo "==> Written $(REQUIREMENTS_FILE):"; \
	cat $(REQUIREMENTS_FILE)

# -----------------------------------------------------------------------------
# Linting and formatting
# -----------------------------------------------------------------------------

lint: ## lint with ruff
	$(CONDA_PREFIX)/bin/ruff check .

lint-fix: ## lint with ruff and auto-fix
	$(CONDA_PREFIX)/bin/ruff check --fix .

format: ## format with ruff
	$(CONDA_PREFIX)/bin/ruff format .
