# Shared Python development targets
# Requires CONDA_PREFIX and PACKAGE_DIR to be defined (or uses defaults)

CONDA_PREFIX ?= $(HOME)/miniforge3
PACKAGE_DIR ?= $(PROJECT_NAME)
REQUIREMENTS_FILE ?= requirements-prod.txt

.PHONY: list-imports requirements lint lint-fix format

list-imports: ## list imports for production requirements
	@$(CONDA_PREFIX)/bin/pipreqs $(PACKAGE_DIR) --print --mode no-pin 2>/dev/null | sort -u

requirements: ## generate pinned production requirements file
	@echo "==> Scanning imports in $(PACKAGE_DIR)..."
	@IMPORTS=$$($(CONDA_PREFIX)/bin/pipreqs $(PACKAGE_DIR) --print --mode no-pin 2>/dev/null | sort -u); \
	if [ -z "$$IMPORTS" ]; then \
		echo "No imports found in $(PACKAGE_DIR)"; \
		exit 1; \
	fi; \
	echo "# Production requirements - generated by make requirements" > $(REQUIREMENTS_FILE); \
	echo "# Source: pipreqs scan of $(PACKAGE_DIR) with versions from conda env" >> $(REQUIREMENTS_FILE); \
	echo "" >> $(REQUIREMENTS_FILE); \
	for pkg in $$IMPORTS; do \
		version=$$($(CONDA_PREFIX)/bin/conda list --no-pip "^$${pkg}$$" 2>/dev/null | grep -v "^#" | awk '{print $$2}' | head -1); \
		if [ -n "$$version" ]; then \
			echo "$${pkg}==$${version}" >> $(REQUIREMENTS_FILE); \
		else \
			pip_version=$$($(CONDA_PREFIX)/bin/pip show "$$pkg" 2>/dev/null | grep "^Version:" | awk '{print $$2}'); \
			if [ -n "$$pip_version" ]; then \
				echo "$${pkg}==$${pip_version}" >> $(REQUIREMENTS_FILE); \
			else \
				echo "$${pkg}" >> $(REQUIREMENTS_FILE); \
			fi; \
		fi; \
	done; \
	echo "==> Written $(REQUIREMENTS_FILE):"; \
	cat $(REQUIREMENTS_FILE)

lint: ## lint with ruff
	$(CONDA_PREFIX)/bin/ruff check .

lint-fix: ## lint with ruff and auto-fix
	$(CONDA_PREFIX)/bin/ruff check --fix .

format: ## format with ruff
	$(CONDA_PREFIX)/bin/ruff format .
